% =============================================================
% ARCHIVO GENERADO por scripts/csv_a_prolog.py. NO EDITAR A MANO.
% Fuente: Fjelstul World Cup Database v1.2.0, (c) 2023 Joshua C.
% Fjelstul, Ph.D., CC-BY-SA 4.0. Ver data/raw/FUENTE.md.
% =============================================================
% Premios individuales. Un premio compartido aparece varias veces.
:- dynamic(premio/3).

% premio(Anio, Premio, Jugador).
premio(1930, bota_de_oro, guillermo_stabile).
premio(1930, bota_de_plata, pedro_cea).
premio(1930, bota_de_bronce, bert_patenaude).
premio(1934, bota_de_oro, oldrich_nejedly).
premio(1934, bota_de_plata, edmund_conen).
premio(1934, bota_de_plata, angelo_schiavio).
premio(1938, bota_de_oro, leonidas).
premio(1938, bota_de_plata, silvio_piola).
premio(1938, bota_de_plata, gyorgy_sarosi).
premio(1938, bota_de_plata, gyula_zsengeller).
premio(1950, bota_de_oro, ademir).
premio(1950, bota_de_plata, oscar_miguez).
premio(1950, bota_de_bronce, estanislau_basora).
premio(1950, bota_de_bronce, chico).
premio(1950, bota_de_bronce, alcides_ghiggia).
premio(1950, bota_de_bronce, telmo_zarra).
premio(1954, bota_de_oro, sandor_kocsis).
premio(1954, bota_de_plata, josef_hugi).
premio(1954, bota_de_plata, max_morlock).
premio(1954, bota_de_plata, erich_probst).
premio(1958, bota_de_oro, just_fontaine).
premio(1958, bota_de_plata, pele).
premio(1958, bota_de_plata, helmut_rahn).
premio(1958, mejor_jugador_joven, pele).
premio(1962, bota_de_oro, florian_albert).
premio(1962, bota_de_oro, garrincha).
premio(1962, bota_de_oro, valentin_ivanov).
premio(1962, bota_de_oro, drazan_jerkovic).
premio(1962, bota_de_oro, leonel_sanchez).
premio(1962, bota_de_oro, vava).
premio(1962, mejor_jugador_joven, florian_albert).
premio(1966, bota_de_oro, eusebio).
premio(1966, bota_de_plata, helmut_haller).
premio(1966, bota_de_bronce, franz_beckenbauer).
premio(1966, bota_de_bronce, ferenc_bene).
premio(1966, bota_de_bronce, geoff_hurst).
premio(1966, bota_de_bronce, valeriy_porkujan).
premio(1966, mejor_jugador_joven, franz_beckenbauer).
premio(1970, bota_de_oro, gerd_muller).
premio(1970, bota_de_plata, jairzinho).
premio(1970, bota_de_bronce, teofilo_cubillas).
premio(1970, mejor_jugador_joven, teofilo_cubillas).
premio(1974, bota_de_oro, grzegorz_lato).
premio(1974, bota_de_plata, johan_neeskens).
premio(1974, bota_de_plata, andrzej_szarmach).
premio(1974, mejor_jugador_joven, wladyslaw_zmuda).
premio(1978, balon_de_oro, mario_kempes).
premio(1978, balon_de_plata, paolo_rossi).
premio(1978, balon_de_bronce, dirceu).
premio(1978, bota_de_oro, mario_kempes).
premio(1978, bota_de_plata, teofilo_cubillas).
premio(1978, bota_de_bronce, rob_rensenbrink).
premio(1978, mejor_jugador_joven, antonio_cabrini).
premio(1982, balon_de_oro, paolo_rossi).
premio(1982, balon_de_plata, falcao).
premio(1982, balon_de_bronce, karl_heinz_rummenigge).
premio(1982, bota_de_oro, paolo_rossi).
premio(1982, bota_de_plata, karl_heinz_rummenigge).
premio(1982, bota_de_bronce, zico).
premio(1982, mejor_jugador_joven, manuel_amoros).
premio(1986, balon_de_oro, diego_maradona).
premio(1986, balon_de_plata, harald_schumacher).
premio(1986, balon_de_bronce, preben_elkjaer).
premio(1986, bota_de_oro, gary_lineker).
premio(1986, bota_de_plata, emilio_butragueno).
premio(1986, bota_de_plata, careca).
premio(1986, bota_de_plata, diego_maradona).
premio(1986, mejor_jugador_joven, enzo_scifo).
premio(1990, balon_de_oro, salvatore_schillaci).
premio(1990, balon_de_plata, lothar_matthaus).
premio(1990, balon_de_bronce, diego_maradona).
premio(1990, bota_de_oro, salvatore_schillaci).
premio(1990, bota_de_plata, tomas_skuhravy).
premio(1990, bota_de_bronce, gary_lineker).
premio(1990, bota_de_bronce, roger_milla).
premio(1990, mejor_jugador_joven, robert_prosinecki).
premio(1994, balon_de_oro, romario).
premio(1994, balon_de_plata, roberto_baggio).
premio(1994, balon_de_bronce, hristo_stoichkov).
premio(1994, bota_de_oro, oleg_salenko).
premio(1994, bota_de_oro, hristo_stoichkov).
premio(1994, bota_de_bronce, kennet_andersson).
premio(1994, bota_de_bronce, romario).
premio(1994, guante_de_oro, michel_preud_homme).
premio(1994, mejor_jugador_joven, marc_overmars).
premio(1998, balon_de_oro, ronaldo).
premio(1998, balon_de_plata, davor_suker).
premio(1998, balon_de_bronce, lilian_thuram).
premio(1998, bota_de_oro, davor_suker).
premio(1998, bota_de_plata, gabriel_batistuta).
premio(1998, bota_de_plata, christian_vieri).
premio(1998, guante_de_oro, fabien_barthez).
premio(1998, mejor_jugador_joven, michael_owen).
premio(2002, balon_de_oro, oliver_kahn).
premio(2002, balon_de_plata, ronaldo).
premio(2002, balon_de_bronce, myung_bo_hong).
premio(2002, bota_de_oro, ronaldo).
premio(2002, bota_de_plata, miroslav_klose).
premio(2002, bota_de_plata, rivaldo).
premio(2002, guante_de_oro, oliver_kahn).
premio(2002, mejor_jugador_joven, landon_donovan).
premio(2006, balon_de_oro, zinedine_zidane).
premio(2006, balon_de_plata, fabio_cannavaro).
premio(2006, balon_de_bronce, andrea_pirlo).
premio(2006, bota_de_oro, miroslav_klose).
premio(2006, bota_de_plata, hernan_crespo).
premio(2006, bota_de_bronce, ronaldo).
premio(2006, guante_de_oro, gianluigi_buffon).
premio(2006, mejor_jugador_joven, lukas_podolski).
premio(2010, balon_de_oro, diego_forlan).
premio(2010, balon_de_plata, wesley_sneijder).
premio(2010, balon_de_bronce, david_villa).
premio(2010, bota_de_oro, thomas_muller).
premio(2010, bota_de_plata, david_villa).
premio(2010, bota_de_bronce, wesley_sneijder).
premio(2010, guante_de_oro, iker_casillas).
premio(2010, mejor_jugador_joven, thomas_muller).
premio(2014, balon_de_oro, lionel_messi).
premio(2014, balon_de_plata, thomas_muller).
premio(2014, balon_de_bronce, arjen_robben).
premio(2014, bota_de_oro, james_rodriguez).
premio(2014, bota_de_plata, thomas_muller).
premio(2014, bota_de_bronce, neymar).
premio(2014, guante_de_oro, manuel_neuer).
premio(2014, mejor_jugador_joven, paul_pogba).
premio(2018, balon_de_oro, luka_modric).
premio(2018, balon_de_plata, eden_hazard).
premio(2018, balon_de_bronce, antoine_griezmann).
premio(2018, bota_de_oro, harry_kane).
premio(2018, bota_de_plata, antoine_griezmann).
premio(2018, bota_de_bronce, romelu_lukaku).
premio(2018, guante_de_oro, thibaut_courtois).
premio(2018, mejor_jugador_joven, kylian_mbappe).
premio(2022, balon_de_oro, lionel_messi).
premio(2022, balon_de_plata, kylian_mbappe).
premio(2022, balon_de_bronce, luka_modric).
premio(2022, bota_de_oro, kylian_mbappe).
premio(2022, bota_de_plata, lionel_messi).
premio(2022, bota_de_bronce, olivier_giroud).
premio(2022, guante_de_oro, emiliano_martinez).
premio(2022, mejor_jugador_joven, enzo_fernandez).
